import {
    inherit as _inherit,
    current as _current,
    transparent as _transparent,
    black as _black,
    white as _white,
    zinc as _zinc,
    red as _red,
    orange as _orange,
    amber as _amber,
    yellow as _yellow,
    lime as _lime,
    green as _green,
    emerald as _emerald,
    teal as _teal,
    cyan as _cyan,
    blue as _blue,
    indigo as _indigo,
    violet as _violet,
    purple as _purple,
    fuchsia as _fuchsia,
    pink as _pink,
    rose as _rose,
    sky as _sky,
    stone as _stone,
    neutral as _neutral,
    gray as _gray,
    slate as _slate,
} from 'tailwindcss/colors';
import { toRGB, withOpacityValue } from '@left4code/tw-starter/dist/js/tailwind-config-helper';

export const content = ['./components/**/*.{js,vue,ts}', './*.{vue,ts,js}', './layouts/**/*.vue', './pages/**/*.vue', './plugins/**/*.{js,ts}', './nuxt.config.{js,ts}', './app.vue'];

export const safelist = [
    'btn-primary',
    'btn-warning',
    'btn-success',
    'btn-dark',
    'btn-secondary',
    'btn-pending',
    'btn-danger',
    'btn-sm',
    'btn-lg',
    'btn-rounded',
    'btn-rounded-primary',
    'btn-rounded-warning',
    'btn-rounded-success',
    'btn-rounded-dark',
    'btn-rounded-secondary',
    'btn-rounded-pending',
    'btn-rounded-danger',

    'text-primary',
    'text-warning',
    'text-success',
    'text-dark',
    'text-secondary',
    'text-pending',
    'text-danger',

    'text-yellow-300',
    'text-yellow-400',
    'text-yellow-500',
    'text-yellow-600',
    'text-yellow-700',

    'text-orange-300',
    'text-orange-400',
    'text-orange-500',
    'text-orange-600',
    'text-orange-700',

    'from-orange-400',
    'to-yellow-400',
    'text-transparent',
    'bg-clip-text',
    'bg-gradient-to-l',
    'from-orange-400',
    'to-yellow-400',
    'md:block',

    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
];
export const darkMode = 'class';
export const theme = {
    extend: {
        fontFamily: {
            script: ['Pacifico', 'handwriting'],
            'script-extra': ['Comforter', 'handwriting'],
        },
        colors: {
            rgb: toRGB({
                inherit: _inherit,
                current: _current,
                transparent: _transparent,
                black: _black,
                white: _white,
                zinc: _zinc,
                red: _red,
                orange: _orange,
                amber: _amber,
                yellow: _yellow,
                lime: _lime,
                green: _green,
                emerald: _emerald,
                teal: _teal,
                cyan: _cyan,
                blue: _blue,
                indigo: _indigo,
                violet: _violet,
                purple: _purple,
                fuchsia: _fuchsia,
                pink: _pink,
                rose: _rose,
                sky: _sky,
                stone: _stone,
                neutral: _neutral,
                gray: _gray,
                slate: _slate,
            }),
            primary: withOpacityValue('--color-primary'),
            'primary-hover': withOpacityValue('--color-primary-hover'),
            alternative: withOpacityValue('--color-alternative'),
            secondary: withOpacityValue('--color-secondary'),
            success: withOpacityValue('--color-success'),
            info: withOpacityValue('--color-info'),
            warning: withOpacityValue('--color-warning'),
            pending: withOpacityValue('--color-pending'),
            danger: withOpacityValue('--color-danger'),
            light: withOpacityValue('--color-light'),
            dark: withOpacityValue('--color-dark'),
            slate: {
                50: withOpacityValue('--color-slate-50'),
                100: withOpacityValue('--color-slate-100'),
                200: withOpacityValue('--color-slate-200'),
                300: withOpacityValue('--color-slate-300'),
                400: withOpacityValue('--color-slate-400'),
                500: withOpacityValue('--color-slate-500'),
                600: withOpacityValue('--color-slate-600'),
                700: withOpacityValue('--color-slate-700'),
                800: withOpacityValue('--color-slate-800'),
                900: withOpacityValue('--color-slate-900'),
            },
            darkmode: {
                50: withOpacityValue('--color-darkmode-50'),
                100: withOpacityValue('--color-darkmode-100'),
                200: withOpacityValue('--color-darkmode-200'),
                300: withOpacityValue('--color-darkmode-300'),
                400: withOpacityValue('--color-darkmode-400'),
                500: withOpacityValue('--color-darkmode-500'),
                600: withOpacityValue('--color-darkmode-600'),
                700: withOpacityValue('--color-darkmode-700'),
                800: withOpacityValue('--color-darkmode-800'),
                900: withOpacityValue('--color-darkmode-900'),
            },
        },
        container: {
            center: true,
        },
        maxWidth: {
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
        },
        strokeWidth: {
            0.5: 0.5,
            1.5: 1.5,
            2.5: 2.5,
        },
        animation: {
            'spin-slow': 'spin 120s linear infinite',
            'bounce-slow': 'bounce 10s linear infinite',
        },
    },
};
export const plugins = [require('@tailwindcss/forms')];
export const variants = {
    extend: {
        boxShadow: ['dark'],
    },
};
